package Presenter;

public enum Events {
    LOGIN, REGISTER,EXIT,ADD_USER_SHOW,PROPERTIES,REPORTS,ADD_SERVICE_WATER,ADD_SERVICE_GAS,ADD_SERVICE_INTERNET,ADD_SERVICE_ELECTRICITY,ADD_BILL,
    ADD_BILL_DIALOG,ACCEPT_REPORT,DELETE;
}
